### ISSUE TITLE
Tool is not go-gettable

### ISSUE THREAD

**Issue by seletskiy** [vishaltelangre/hostsconfig#1]
```
$ go get github.com/vishaltelengre/hostsconfig
$ hostsconfig -l
2015/12/01 18:24:07 open ./templates/standard: no such file or directory
```

The error occurs because of you are using template files which are located in the text files, accessed by relative paths.

To fix this issue you should embed templates contents directly into the source code, like this: https://github.com/seletskiy/go-makepkg/blob/master/service.go

**Comment by vishaltelangre** [comment]
@seletskiy Thanks for reporting this issue. I will push an update soon.
